CREATE SEQUENCE REPLY_ID_SEQUENCE
    INCREMENT BY 1
    START WITH 1
    NOCACHE;

CREATE SEQUENCE POST_ID_SEQUENCE
    INCREMENT BY 1
    START WITH 1
    NOCACHE;

CREATE TABLE TEST_POST(
    POST_ID NUMBER PRIMARY KEY,
    POST_TITLE VARCHAR2(30),
    POST_CONTENT VARCHAR2(200),
    USERID VARCHAR2(100),
    VIEWS NUMBER,
    WRITE_DATE DATE,
    CONSTRAINT FK_USERID_POST FOREIGN KEY(USERID) REFERENCES TEST_MEMBER(USERID)
);

CREATE TABLE TEST_REPLY(
    REPLY_ID NUMBER PRIMARY KEY,
    POST_ID NUMBER,
    USERID VARCHAR(100),
    REPLY_CONTENT VARCHAR(100),
    WRITE_DATE DATE,
    CONSTRAINT FK_POST_ID_REPLY FOREIGN KEY(POST_ID) REFERENCES TEST_POST(POST_ID),
    CONSTRAINT FK_USERID_REPLY FOREIGN KEY(USERID) REFERENCES TEST_MEMBER(USERID)
);

SELECT * FROM (
SELECT TEST_POST.*, ROW_NUMBER() OVER(ORDER BY POST_ID) AS RN FROM TEST_POST
) WHERE RN BETWEEN 1 AND 10;

INSERT INTO TEST_POST(POST_ID, POST_TITLE, POST_CONTENT, USERID, VIEWS, WRITE_DATE)
VALUES(POST_ID_SEQUENCE.NEXTVAL, '첫 번째 포스트', '이것은 첫 번째 포스트의 내용입니다.', 'test3', 50, TO_DATE('2024-04-05', 'YYYY-MM-DD'));

INSERT INTO TEST_POST(POST_ID, POST_TITLE, POST_CONTENT, USERID, VIEWS, WRITE_DATE)
VALUES(POST_ID_SEQUENCE.NEXTVAL, '두 번째 포스트', '이것은 두 번째 포스트의 내용입니다.', 'test3', 70, TO_DATE('2024-04-04', 'YYYY-MM-DD'));

INSERT INTO TEST_POST(POST_ID, POST_TITLE, POST_CONTENT, USERID, VIEWS, WRITE_DATE)
VALUES(POST_ID_SEQUENCE.NEXTVAL, '세 번째 포스트', '이것은 세 번째 포스트의 내용입니다.', 'test3', 60, TO_DATE('2024-04-03', 'YYYY-MM-DD'));

INSERT INTO TEST_POST(POST_ID, POST_TITLE, POST_CONTENT, USERID, VIEWS, WRITE_DATE)
VALUES(POST_ID_SEQUENCE.NEXTVAL, '네 번째 포스트', '이것은 네 번째 포스트의 내용입니다.', 'test3', 80, TO_DATE('2024-04-02', 'YYYY-MM-DD'));

INSERT INTO TEST_POST(POST_ID, POST_TITLE, POST_CONTENT, USERID, VIEWS, WRITE_DATE)
VALUES(POST_ID_SEQUENCE.NEXTVAL, '다섯 번째 포스트', '이것은 다섯 번째 포스트의 내용입니다.', 'test3', 90, TO_DATE('2024-04-01', 'YYYY-MM-DD'));

INSERT INTO TEST_POST(POST_ID, POST_TITLE, POST_CONTENT, USERID, VIEWS, WRITE_DATE)
VALUES(POST_ID_SEQUENCE.NEXTVAL, '여섯 번째 포스트', '이것은 여섯 번째 포스트의 내용입니다.', 'test3', 100, TO_DATE('2024-03-31', 'YYYY-MM-DD'));

INSERT INTO TEST_POST(POST_ID, POST_TITLE, POST_CONTENT, USERID, VIEWS, WRITE_DATE)
VALUES(POST_ID_SEQUENCE.NEXTVAL, '일곱 번째 포스트', '이것은 일곱 번째 포스트의 내용입니다.', 'test3', 110, TO_DATE('2024-03-30', 'YYYY-MM-DD'));

INSERT INTO TEST_POST(POST_ID, POST_TITLE, POST_CONTENT, USERID, VIEWS, WRITE_DATE)
VALUES(POST_ID_SEQUENCE.NEXTVAL, '여덟 번째 포스트', '이것은 여덟 번째 포스트의 내용입니다.', 'test3', 120, TO_DATE('2024-03-29', 'YYYY-MM-DD'));

INSERT INTO TEST_POST(POST_ID, POST_TITLE, POST_CONTENT, USERID, VIEWS, WRITE_DATE)
VALUES(POST_ID_SEQUENCE.NEXTVAL, '아홉 번째 포스트', '이것은 아홉 번째 포스트의 내용입니다.', 'test3', 130, TO_DATE('2024-03-28', 'YYYY-MM-DD'));

INSERT INTO TEST_POST(POST_ID, POST_TITLE, POST_CONTENT, USERID, VIEWS, WRITE_DATE)
VALUES(POST_ID_SEQUENCE.NEXTVAL, '열 번째 포스트', '이것은 열 번째 포스트의 내용입니다.', 'test3', 140, TO_DATE('2024-03-27', 'YYYY-MM-DD'));

commit;
SELECT * FROM (SELECT TEST_POST.*, ROW_NUMBER() OVER (ORDER BY POST_ID DESC) AS RN FROM TEST_POST)
WHERE RN BETWEEN 1 AND 20;


            
            