CREATE SEQUENCE REPLY_ID_SEQUENCE
    INCREMENT BY 1
    START WITH 1
    NOCACHE;

CREATE SEQUENCE POST_ID_SEQUENCE
    INCREMENT BY 1
    START WITH 1
    NOCACHE;

CREATE TABLE TEST_POST(
    POST_ID NUMBER PRIMARY KEY,
    POST_TITLE VARCHAR2(30),
    POST_CONTENT VARCHAR2(200),
    USERID VARCHAR2(100),
    VIEWS NUMBER,
    WRITE_DATE DATE,
    CONSTRAINT FK_USERID_POST FOREIGN KEY(USERID) REFERENCES TEST_MEMBER(USERID)
);

CREATE TABLE TEST_REPLY(
    REPLY_ID NUMBER PRIMARY KEY,
    POST_ID NUMBER,
    USERID VARCHAR(100),
    REPLY_CONTENT VARCHAR(100),
    WRITE_DATE DATE,
    CONSTRAINT FK_POST_ID_REPLY FOREIGN KEY(POST_ID) REFERENCES TEST_POST(POST_ID),
    CONSTRAINT FK_USERID_REPLY FOREIGN KEY(USERID) REFERENCES TEST_MEMBER(USERID)
);

SELECT * FROM (
SELECT TEST_POST.*, ROW_NUMBER() OVER(ORDER BY POST_ID) AS RN FROM TEST_POST
) WHERE RN BETWEEN 1 AND 10;



    